11225: &default112
  cuts:
    - { t0: 134, tf:  138, threshold:  120, type: higher, filter: 14, stop: false , npop: "max"}
    - { t0: 134, tf:  138, threshold:  240, type:  lower, filter: 14, stop: false , npop: "max"}
    - { t0:   0, tf:  125, threshold:    6, type:  lower, filter: 14, stop: false , npop: "max"}
    - { t0:   0, tf:  125, threshold:  -6., type: higher, filter: 14, stop: false , npop: "min"}
    - { t0: 125, tf: 1024, threshold: -30., type: higher, filter: 10, stop: false , npop: "max"}
    - { t0: 375, tf: 1024, threshold: -6.2, type: higher, filter: 10, stop: false , npop: "max"}
    - { t0: 200, tf: 1024, threshold:   30, type:  lower, filter: 10, stop: false , npop: "max"}
    - { t0: 160, tf: 1024, threshold:   75, type:  lower, filter: 10, stop: false , npop: "max"}

11227: 
  <<: *default112

# 11114: &default111
#   cuts:
    # - { t0: 134, tf:  138, threshold:   50, type: higher, filter: 2, stop: false , npop: "max"}
    # - { t0: 134, tf:  138, threshold:   50, type: higher, filter: 2, stop: false , npop: "min"}
    # - { t0: 134, tf:  138, threshold:   90, type:  lower, filter: 2, stop: false , npop: "max"}
    # - { t0: 140, tf: 1024, threshold:  100, type:  lower, filter: 10, stop: false , npop: "max"}
    # - { t0: 200, tf: 1024, threshold:   12, type:  lower, filter: 10, stop: false , npop: "max"}
    # - { t0: 200, tf: 1024, threshold: -30., type:  higher, filter: 10, stop: false , npop: "min"}
    # - { t0: 200, tf:  300, threshold:  0.5, type:  lower, filter: 10, stop: false , npop: "max"}
    # - { t0: 300, tf:  325, threshold:  5, type:  lower, filter: 10, stop: false , npop: "max"}
    # - { t0: 210, tf:  240, threshold: -28., type:  higher, filter: 10, stop: false , npop: "min"}
    # - { t0: 500, tf: 1024, threshold: -20., type: higher, filter: 14, stop: false , npop: "min"}
    # - { t0: 100, tf:  400, threshold: -30., type: higher, filter: 24, stop: false , npop: "min"}
    # - { t0: 400, tf: 1024, threshold:   12, type:  lower, filter: 14, stop: false , npop: "max"}
    # - { t0:   0, tf:  125, threshold:    6, type:  lower, filter: 14, stop: false , npop: "max"}
    # - { t0:   0, tf:  125, threshold:  -6., type: higher, filter: 14, stop: false , npop: "min"}
    # - { t0: 125, tf: 1024, threshold: -30., type: higher, filter: 10, stop: false , npop: "max"}
    # - { t0: 375, tf: 1024, threshold: -6.2, type: higher, filter: 10, stop: false , npop: "max"}
    # - { t0: 160, tf: 1024, threshold:   75, type:  lower, filter: 10, stop: false , npop: "max"}

11114: &default111
  cuts:
    - { t0: 134, tf:  138, threshold:   50, type: higher, filter: 2, stop: false , npop: "max"}
    - { t0: 134, tf:  138, threshold:   90, type:  lower, filter: 2, stop: false , npop: "max"}
    - { t0: 200, tf: 1024, threshold:   100, type:  lower, filter: 10, stop: false , npop: "max"}
    - { t0:   0, tf:  125, threshold:    6, type:  lower, filter: 14, stop: false , npop: "max"}
    - { t0:   0, tf:  125, threshold:  -6., type: higher, filter: 14, stop: false , npop: "min"}

11116:
  <<: *default111

