# Path to the files.txt containing the Rucio's paths
filepath_folder: "/eos/experiment/neutplatform/protodune/experiments/ProtoDUNE-II/PDS_Commissioning/waffles/1_rucio_paths/"

# Name of the folder where the txt files containing FFTs will be saved
# No "/" in the name!
fft_folder: "FFTs_txt"

# Name of the folder where the set of FFTs will be saved (set == all the FFTs of a given configuration)
# No "/" in the name!
fft_set_folder: "Configs/ConfigXXX"

# File with the daphne-channel <-> Offline channel mapping
# The new channel map is the one after 24 September 2024
# Note: run number > 30000 == new channel mapdaphne_to_offline_dictF
channel_map_file: "PDHD_PDS_ChannelMap.csv"
new_channel_map_file: "PDHD_PDS_NewChannelMap.csv"

# All the noise runs acquired in NP04
# Dictionary with the noise run <-> Vgain setting
run_vgain_dict:
  26319: 2700
  26363: 2700
  26378: 2700
  26438: 2700
  26490: 2700
  27875: 2318
  27877: 2318
  31913: 3192
  31914: 3192
  31915: 2926
  31916: 2926
  31917: 2793
  31919: 2793
  31920: 2660
  31921: 2660
  31922: 2527
  31923: 2527
  31924: 2394
  31925: 2394
  31926: 2261
  31927: 2261
  31928: 2128
  31929: 2128
  31930: 1995
  31931: 1995
  31932: 1862
  31933: 1862
  31934: 1729
  31935: 1729
  31936: 1596
  31937: 1596
  31938: 1463
  31939: 1463
  31940: 1330
  31941: 1330
  31942: 1197
  31943: 1197
  31944: 1064
  31945: 1064
  31946: 931
  31947: 931
         
# Runs where DAPHNE instegrators were ON
integratorsON_runs: [26319, 26363, 26378, 26438, 26490, 27875, 27877]

# Runs where some DAPHNEs were in full streaming mode 
fullstreaming_runs: [27877]

# Run-channel to ignore
# Ignore because of digital jumps / wfs out of dynamic range / ...
# If you don't want to ignore any channel, just leave it empty
ignore_ch_dict:
  27877: [10512, 10700, 10702, 10705, 10707, 10710, 10712, 10715, 10717, 10910, 10911, 10913, 10914, 10916, 10917]
  31046: [10903, 10904, 10905]
  31913: [10410, 10417]
  31914: [11300, 11302, 11305, 11307]
  31915: [10410, 10417]
  31916: [11300, 11302, 11305, 11307]
  31917: [10410, 10411, 10417]
  31919: [11300, 11302, 11305, 11307]
  31920: [10410, 10417]
  31921: [11143, 11300, 11302, 11305, 11307]
  31922: [10410, 10411, 10417]
  31923: [11300, 11302, 11305, 11307]
  31924: [10410, 10411, 10417]
  31925: [11300, 11302, 11305, 11307]
  31926: [10410, 10417]
  31927: [11300, 11302, 11305, 11307]
  31928: [10410, 10417]
  31929: [11300, 11302, 11305, 11307]
  31930: [10410, 10411, 10417]
  31931: [11300, 11302, 11305, 11307]
  31932: [10410, 10417]
  31933: [11300, 11302, 11305, 11307]
  31934: [10410, 10411, 10417]
  31935: [11300, 11302, 11305, 11307]
  31936: [10410, 10417]
  31938: [10410, 10417]
  31939: [11300, 11302, 11305, 11307]
  31940: [10410, 10417, 10432, 10927, 10940, 10942, 10943, 10944]
  31941: [11110, 11300, 11302, 11305, 11307]
  31942: [10400, 10410, 10417, 10432, 10902, 10920, 10921, 10922, 10925, 10926, 10927, 10930, 10932, 10935, 10936, 10937, 10940, 10941, 10942, 10943, 10944, 10945, 10946, 10947]
  31943: [11103, 11110, 11115, 11124, 11141, 11144, 11220, 11227, 11300, 11302, 11305, 11307]
  31944: [10400, 10405, 10407, 10410, 10411, 10412, 10417, 10427, 10430, 10431, 10432, 10435, 10436, 10440, 10442, 10443, 10444, 10446, 10900, 10902, 10906, 10910, 10915, 10920, 10921, 10924, 10925, 10926, 10927, 10930, 10931, 10932, 10933, 10934, 10935, 10936, 10937, 10940, 10941, 10942, 10943, 10944, 10945, 10946, 10947]
  31945: [11100, 11103, 11110, 11115, 11124, 11127, 11140, 11141, 11142, 11143, 11144, 11145, 11220, 11222, 11227, 11232, 11240, 11300, 11302, 11305, 11307]
  31946: [10400, 10402, 10404, 10405, 10406, 10407, 10410, 10411, 10412, 10413, 10414, 10415, 10416, 10417, 10422, 10426, 10427, 10430, 10431, 10432, 10434, 10435, 10436, 10437, 10440, 10442, 10443, 10444, 10446, 10447, 10900, 10902, 10903, 10904, 10905, 10906, 10907, 10910, 10912, 10915, 10916, 10920, 10921, 10924, 10925, 10926, 10927, 10930, 10931, 10932, 10933, 10934, 10935, 10936, 10937, 10940, 10941, 10942, 10943, 10944, 10945, 10946, 10947]
  31947: [11100, 11101, 11102, 11103, 11106, 11107, 11110, 11111, 11115, 11116, 11120, 11124, 11126, 11127, 11130, 11132, 11133, 11134, 11135, 11136, 11137, 11140, 11141, 11142, 11143, 11144, 11145, 11146, 11200, 11202, 11203, 11204, 11205, 11210, 11213, 11215, 11216, 11220, 11221, 11222, 11223, 11224, 11227, 11230, 11231, 11232, 11240, 11245, 11247, 11300, 11302, 11305, 11307]

# Golden HPK and FBK Offline channels (no low freq. spikes)
golden_ch_dict:
  "HPK": 0
  "FBK": 72
